package cl.duoc.speedfast.model;

/**
 *  REPRESENTA TRES INSTANCIAS UNICAS DE ESTADO DE UN PEDIDO PARA MEJORAR LA LEGIBILIDAD Y EVITAR ERRORES DE TIPEO
 */

public enum EstadoPedido {
    PENDIENTE, EN_REPARTO, ENTREGADO
}